---
- name: Update apt cache
  apt:
    update_cache: yes
    
- name: Install Python 3
  apt:
    name: python3
    state: present

- name: Install pip
  apt:
    name: python3-pip
    state: present

- name: Install boto3 using pip3
  become: true
  pip:
    name: boto3
    state: present

- name: Install AWS CLI using pip
  become: true
  pip:
    name: awscli
    state: latest
    executable: pip3

- name: Fix broken packages
  apt:
    name: "*"
    state: latest
    force: yes

- name: Add Ubuntu Focal repository
  apt_repository:
    repo: "deb http://archive.ubuntu.com/ubuntu focal main universe"

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Java JDK 17
  apt:
    name: openjdk-17-jdk
    state: present
    

